---
- name: task for install httpd service
  hosts: all
  become: true

  tasks:
    - name: install httpd service
      yum:
        name: httpd
        state: present
        
    - name: start tree package
      yum:
        name: tree
        state: present
