---
- name: task for install httpd service
  hosts: all
  become: true

  tasks:
    - name: install httpd service
      yum:
        name: httpd
        state: present

    - name: start httpd service
      service:
        name: httpd
        state: started
        enabled: true
        
          
        
    - name: remove tree package
      yum:
        name: tree
        state: present
